---
name: ""
swversion: ""
apiversion: ""
mac: "EE:9C:83:5D:B5:56"
ipaddress: ""
gateway: ""
netmask: ""
bridgeid: EE9C83FFFE5DB556
timezone: ""
linkbutton:
  lastlinkbuttonpushed: 0
  pressed: false
hue_users:
  0:
    devicetype: "Hue Essentials#SM-G781B"
    client_key: f3b4958c52a111e78008010203040506
    date_created: "1656371067"
    date_last_connected: "1656371067"
